#define 整数 int
#define 文字 char
#define ミニプログラム void
#define 戻る return
#define 表示 printf
#define その間繰り返す while
#define もし if
#define そうでなければ else
#define 空 NULL
#define 秒待つ sleep
#define スレッド箱 pthread_t
#define スレッド作成 pthread_create
#define スレッド完了まで待つ pthread_join
#define iに1を足す ++i